### ISSUE TITLE
Question: Why do you use dispatch instead of navigate?

### ISSUE THREAD

**Issue by cihadturhan** [nihgwu/react-native-dva-starter#31]
I wonder why you use longer form:
```javascript
import {NavigationActions} from 'react-navigation'
...
this.props.dispatch(NavigationActions.navigate({routeName: 'HomeScreen'}));
```
Is there a problem with the code below?
```javascript
this.props.navigation.navigate('HomeScreen');
```
Do we really need, importing `NavigationActions` for each time we need navigation

**Comment by nihgwu** [comment]
That's a good question, in screen components, we can simply use `navigation` instead of `dispatch`, but in other components, we have to use `dispatch`

Actually `this.props.navigation.navigate('HomeScreen');` is a convenient way to perform `this.props.dispatch(NavigationActions.navigate({routeName: 'HomeScreen'}));` created by `addNavigationHelpers`

**Comment by cihadturhan** [comment]
Thanks for shedding light.

> but in other components, we have to use dispatch

By other components, you mean the components do not use `@connect()`, right?

**Comment by nihgwu** [comment]
components with `@connect()` witch provides the `dispatch` method

**Comment by cihadturhan** [comment]
I see. Thank you very much @nihgwu. Closing.
